# Generated by Django 4.0.4 on 2022-04-23 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_customer_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_paid', 'Не оплачено'), ('paid', 'Оплачено')], default='not_paid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('costomer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.customer')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
