# Generated by Django 4.0.4 on 2022-04-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(limit_choices_to={'status': 'not_paid'}, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='category.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='category.product')),
            ],
            options={
                'verbose_name': 'Пункт заказа',
                'verbose_name_plural': 'пункт заказов',
                'unique_together': {('product', 'order')},
            },
        ),
    ]
