# Generated by Django 4.0.4 on 2022-04-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='costomer',
            new_name='customer',
        ),
    ]
