# Generated by Django 4.0.4 on 2022-04-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_rename_costomer_order_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
    ]
