# Generated by Django 4.0.4 on 2022-04-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='costomer',
        ),
    ]
